# Novelty + data Params
scenario: nc
scenario_classif: class
exp_type: class
num_per_task: 1
num_classes_first: 2
dset_name: svhn
experiment_name: inc_1class
num_threads: 6
num_workers: 4
data_dir: ./data
dir_results: ./Results
# net_type: resnet50_contrastive
net_type: resnet18


# When training: 


# for baselines:
batchsize: 50
num_epochs: 10
cut_epoch_short: False
keep_all_data: False
coreset_size: 0
finetune_backbone: 'off'
use_image_as_input: False
only_novelty: True

# ------ for ODIN
# novelty_detector: odin
# only_novelty: False
# detector_params:
#   similarity: cosine
#   score_func: logit
#   noise_magnitude: 0.02
#   weight_decay: 0.0001
# experiment_name_plot: odin_cosine_h_0.02_10-3


# ------- for DFM 
novelty_detector: dfm
detector_params:
  pca_level: 0.995
  score_type: pca
  n_components: None
  n_percent_comp: 0.2
experiment_name_plot: dfm


# ------- If doing latent replay, else comment.
# latent_layer_name: 'FC.3'
# weight_latent: 0.5
# percent_latent: 0.05 
# weight_old: 0.95
