# Novelty + data Params
scenario: nc
scenario_classif: instance
exp_type: instance
dset_name: core50
experiment_filepath: ./experiments/core50/inc_instance
num_threads: 6
num_workers: 4
data_dir: ./data
dir_results: ./Results
net_type: resnet50_contrastive
# net_type: resnet18


# When training: 
# batchsize: 50
# num_epochs: 10
# coreset_size: 1000
# cut_epoch_short: False

# for baselines:
batchsize: 50
num_epochs: 10
keep_all_data: False
finetune_backbone: 'off'
coreset_size: 0
cut_epoch_short: False
only_novelty: True
use_image_as_input: False

# ------ for ODIN
# novelty_detector: odin
# only_novelty: False
# detector_params:
#   similarity: baseline
#   score_func: logit
#   noise_magnitude: 0.02
#   weight_decay: 0.0001
# experiment_name_plot: odin_cosine_h_0.02_10-3


# ------- for DFM 
novelty_detector: dfm
detector_params:
  pca_level: 0.995
  score_type: pca
experiment_name_plot: dfm_pca_0.995


# ------- If doing latent replay, else comment.
# latent_layer_name: 'FC.3'
# weight_latent: 0.5
# percent_latent: 0.05 
# weight_old: 0.95
